### ISSUE TITLE
Validation without heap allocations

### ISSUE THREAD

**Issue by janrueth** [jedisct1/rust-jwt-simple#77]
Hey,
are there any plans to remove the heap allocations from the verification code path? Or have a variant that does not dynamically allocate?

From looking through the code, it seems that allocations are only performed for base64 decoding (header, auth tag, claims).
The header is limited to 8kB. So the b64-decoded version is also bound by this, and could be on the stack.

The authentication tag length depends on the employed signature scheme and could be provided from the respective trait's verify_token method. For EC, these are twice the key length.  For RSA, the decoded signature cannot exceed the modulus size which is likely not exceeding 4096 bit. Similar for HMAC, the signature is bound by the hash function's output size.

The size of the claims is practically limited (e.g., if the token comes from a header, the header is usually limited in size) and is likely known by the caller and could be provided to the verify_token methods.

**Comment by jedisct1** [comment]
Hi!

There's probably a lot of hidden memory allocations, including in dependencies (which may block updating them, if they don't do allocations now, but more recent versions do).

Using static buffers is also a security risk, as carefully adding overflow checks everywhere becomes mandatory in order to avoid panics.

It would also require breaking API changes, which is not desirable.

However, there will eventually be a port of that library to Zig, that makes it way easier to avoid heap allocations.
